build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - sh infra/build.sh

deploy-production:
  only:
    - master
  stage: deploy
  image: dtzar/helm-kubectl:latest
  script:
    - sh infra/deploy.sh
  environment:
    name: Production
    url: https://loalang.xyz

deploy-staging:
  only:
    - branches
  except:
    - master
  stage: deploy
  image: dtzar/helm-kubectl:latest
  script:
    - sh infra/deploy.sh $CI_ENVIRONMENT_SLUG
  variables:
    API_URL: https://$CI_ENVIRONMENT_SLUG.staging.api.loalang.xyz
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.staging.loalang.xyz
    on_stop: clean-staging

clean-staging:
  stage: deploy
  image: dtzar/helm-kubectl:latest
  variables:
    GIT_STRATEGY: none
  script:
    - helm delete loalang-$CI_ENVIRONMENT_SLUG
  environment:
    name: $CI_COMMIT_REF_NAME
    action: stop
  when: manual
