version: "3.7"
services:
  www:
    image: registry.gitlab.com/loalang/loalang.xyz/www:${WWW_TAG}

  api:
    image: registry.gitlab.com/loalang/loalang.xyz/api:${API_TAG}
    environment:
      AUTH_HOST: http://auth
      PKG_HOST: http://pkg
      SEARCH_HOST: http://search
      DOCS_HOST: http://docs

  auth:
    image: registry.gitlab.com/loalang/loalang.xyz/auth:${AUTH_TAG}
    environment:
      TOKEN_ENCRYPTION_PRIVATE_KEY: ${TOKEN_ENCRYPTION_PRIVATE_KEY}

  search:
    image: registry.gitlab.com/loalang/loalang.xyz/search:${SEARCH_TAG}
    environment:
      ALGOLIA_APPLICATION_ID: ${ALGOLIA_APPLICATION_ID}
      ALGOLIA_ADMIN_KEY: ${ALGOLIA_ADMIN_KEY}
      AMQP_URL: ${AMQP_URL}

  pkg:
    image: registry.gitlab.com/loalang/loalang.xyz/pkg:${PKG_TAG}
    environment:
      AMQP_URL: ${AMQP_URL}

  docs:
    image: registry.gitlab.com/loalang/loalang.xyz/docs:${DOCS_TAG}
    environment:
      AMQP_URL: ${AMQP_URL}
