version: "3.7"
services:
  ingress:
    image: registry.gitlab.com/loalang/loalang.xyz/ingress:${INGRESS_TAG}
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/core/.caddy:/root/.caddy
    environment:
      CLOUDFLARE_EMAIL: ${CLOUDFLARE_EMAIL}
      CLOUDFLARE_API_KEY: ${CLOUDFLARE_API_KEY}

  auth:
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASS}
      PASSWORD_HASH_SALT: ${PASSWORD_HASH_SALT}

  search:
    environment:
      ALGOLIA_INDEX: prod_search

  pkg:
    volumes:
      - /etc/google/credentials.json:/etc/google/credentials.json
    environment:
      NEO4J_HOST: ${NEO4J_HOST}
      NEO4J_USER: ${NEO4J_USER}
      NEO4J_PASS: ${NEO4J_PASS}
      GOOGLE_APPLICATION_CREDENTIALS: /etc/google/credentials.json

  docs:
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASS: ${REDIS_PASS}
