version: "3.7"
services:
  www:
    image: gitlab.com/loalang/loalang.xyz/www-builder
    build:
      context: ..
      dockerfile: ./infra/docker/services/www/builder.dockerfile
    volumes:
      - ../services/www:/project
    command: ["yarn", "start"]
    ports:
      - 8090:3000
    environment:
      REACT_APP_API_URL: http://localhost:8091
      REACT_APP_VERSION: latest

  api:
    image: gitlab.com/loalang/loalang.xyz/api-builder
    build:
      context: ..
      dockerfile: ./infra/docker/services/api/builder.dockerfile
    volumes:
      - ../services/api:/project
    command: ["yarn", "start"]
    ports:
      - 8091:80

  auth:
    image: gitlab.com/loalang/loalang.xyz/auth-builder
    build:
      context: ..
      dockerfile: ./infra/docker/services/auth/builder.dockerfile
    volumes:
      - ../services/auth:/project
    command: ["yarn", "start"]
    ports:
      - 8092:80
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASS: <<database-password>>
      PASSWORD_HASH_SALT: <<salt>>
    depends_on:
      - postgres

  search:
    image: gitlab.com/loalang/loalang.xyz/search-builder
    build:
      context: ..
      dockerfile: ./infra/docker/services/search/builder.dockerfile
    volumes:
      - ../services/search:/project
    command: ["yarn", "start"]
    ports:
      - 8093:80
    environment:
      ALGOLIA_INDEX: dev_search

  pkg:
    image: gitlab.com/loalang/loalang.xyz/pkg-builder
    build:
      context: ..
      dockerfile: ./infra/docker/services/pkg/builder.dockerfile
    volumes:
      - ../services/pkg:/project
      - ${LOCAL_GOOGLE_CREDENTIALS_FILE}:/mnt/credentials.json
    command: ["yarn", "start"]
    ports:
      - 8094:80
    environment:
      NEO4J_HOST: neo4j
      NEO4J_USER: neo4j
      NEO4J_PASS: neo4j
      GOOGLE_APPLICATION_CREDENTIALS: /mnt/credentials.json
    depends_on:
      - neo4j

  docs:
    image: gitlab.com/loalang/loalang.xyz/docs-builder
    build:
      context: ..
      dockerfile: ./infra/docker/services/docs/builder.dockerfile
    volumes:
      - ../services/docs:/project
    command: ["yarn", "start"]
    ports:
      - 8095:80
    environment:
      REDIS_PASS: null
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis

  notebooks:
    image: gitlab.com/loalang/loalang.xyz/notebooks-builder
    build:
      context: ..
      dockerfile: ./infra/docker/services/notebooks/builder.dockerfile
    volumes:
      - ../services/notebooks:/project
    command: ["yarn", "start"]
    ports:
      - 8096:80
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASS: <<database-password>>
    depends_on:
      - postgres

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: <<database-password>>
      POSTGRES_USER: postgres
    volumes:
      - ../.db/postgres:/var/lib/postgresql/data
      - ../services/auth/schema.sql:/docker-entrypoint-initdb.d/auth.sql
      - ../services/notebooks/schema.sql:/docker-entrypoint-initdb.d/notebooks.sql
      - ./dev/pg_hba.sh:/docker-entrypoint-initdb.d/pg_hba.sh
      - ./dev/postgres.conf:/etc/postgres.conf
    ports:
      - 5432:5432
    command: postgres --config_file=/etc/postgres.conf

  neo4j:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_AUTH: none
    volumes:
      - ../.db/neo4j:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ../.db/redis:/data
