apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "loalang.fullname" . }}
  labels:
{{ include "loalang.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: elasticsearch:7.4.2
          env:
            - name: ELASTIC_HOST
              value: http://loalang-elastic:9200
            - name: discovery.type
              values: single-node
            - name: bootstrap.memory_lock
              values: "true"
            - name: ES_JAVA_OPTS
              values: -Xms750m -Xmx750m
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          livenessProbe:
            tcpSocket:
              port: transport
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /_cluster/health
              port: http
            initialDelaySeconds: 20
            timeoutSeconds: 5
