replicaCount: 1

image:
  repository: registry.gitlab.com/loalang/loalang.xyz/www
  pullPolicy: Always

imagePullSecrets:
  - name: regcred

service:
  type: LoadBalancer
  port: 80

host: loalang.xyz
