{{- if .Values.host -}}
{{- $fullName := include "loalang.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  labels:
{{ include "loalang.labels" . | indent 4 }}
spec:
  tls:
    - hosts:
        - {{ include "loalang.host" . | quote }}
      secretName: {{ $fullName }}-cert
  rules:
    - host: {{ include "loalang.host" . | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
{{- end }}
