apiVersion: v1
kind: Service
metadata:
  name: {{ include "loalang.fullname" . }}
  labels:
{{ include "loalang.labels" . | indent 4 }}
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loalang.fullname" . }}-elastic
  labels:
{{ include "loalang.labels" . | indent 4 }}
spec:
  ports:
    - port: 9200
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}-elastic
    app.kubernetes.io/instance: {{ .Release.Name }}
