name: Deploy on Push

on:
  push:
    branches:
      - master
      - refresh

jobs:
  build-service:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - api
          - search
          - auth
          - pkg
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.6'

      - name: Setup Protobuf
        uses: arduino/setup-protoc@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Go for Protobuf
        run: go get -u github.com/golang/protobuf/protoc-gen-go

      - name: Codegen
        run: make generate

      - name: Set VERSION
        run: echo ::set-env name=VERSION::${{ hashFiles(format('{0}/**', matrix.service)) }}

      - name: Set SERVICE
        run: echo ::set-env name=SERVICE::${{ matrix.service }}

      - name: Set ENVIRONMENT
        run: echo ::set-env name=ENVIRONMENT::$(test "${{ github.ref }}" = "refs/heads/master" && echo production || echo staging)

      - name: Authenticate Docker
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Pull latest version
        run: docker pull docker.pkg.github.com/loalang/loalang.xyz/$SERVICE:$VERSION || true

      - name: Build new version
        run: docker build --cache-from docker.pkg.github.com/loalang/loalang.xyz/$SERVICE:latest -t docker.pkg.github.com/loalang/loalang.xyz/$SERVICE:$VERSION $SERVICE

      - name: Push new version
        run: docker push docker.pkg.github.com/loalang/loalang.xyz/$SERVICE:$VERSION

      - name: Deploy
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with: 
          args: --namespace ${{ env.ENVIRONMENT }} set image deployment/${{ env.SERVICE }} ${{ env.SERVICE }}=docker.pkg.github.com/loalang/loalang.xyz/${{ env.SERVICE }}:${{ env.VERSION }} --record
